### ISSUE TITLE
Add markdown toolbar

### ISSUE THREAD

**Issue by robsonsobral** [writewithocto/ink#15]
Hi!

This is an idea, actually.

In my experience, markdown is simple but scary for newbies. Toolbars help new users to learn markdown. You could go one step ahead and hide the markup on element blur, as they are drawing a lot of attention right now.

Thank you!

**Comment by robsonsobral** [comment]
Screenshot from this form itself:

![image](https://user-images.githubusercontent.com/931642/161453066-f7f37521-a1b4-486b-8dad-ee18bc5ef234.png)

As a suggestion.

**Comment by robsonsobral** [comment]
O selection, the toolbar could appear over it, like Medium does.

**Comment by voraciousdev** [comment]
@robsonsobral, I started on this feature earlier this week. I'll likely go for a static toolbar that can anchor to the top or bottom of the editor for the initial release, but I'm open to the idea of a floating toolbar as well.
