### ISSUE TITLE
Which flavor of Markdown?

### ISSUE THREAD

**Issue by robsonsobral** [writewithocto/ink#16]
Which flavor of Markdown is supported? [CommonMark](https://commonmark.org/)? Shouldn't it be added to the `readme.md`?

It would be good to support [Markdown Extra](https://michelf.ca/projects/php-markdown/extra), so **Ink** could be used within system which render using the original PHP lib.

**Comment by voraciousdev** [comment]
@robsonsobral, Ink currently supports [GFM](https://github.github.com/gfm/) which is a superset of CommonMark. I'll leave this issue open as a task to update the README. As for Markdown Extra, I'll have to dig in and see what it would take to add support.

**Comment by robsonsobral** [comment]
I'm not sure all features can be implemented using Markdown-it, but some can. However, I know nothing about CodeMirror.
